name: arctekko
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  get: ^3.4.6
  dio: ^3.0.10
  logger: ^0.9.2
  get_storage: ^1.3.0
  hive: ^1.4.3
  darq: ^0.4.0+1
  retrofit: ^1.3.4
  cached_network_image: ^2.3.1
  extended_image: ^1.1.1
  pull_to_refresh: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1
  json_serializable: ^3.4.0
  retrofit_generator: ^1.3.7+5
  hive_generator: ^0.7.1

flutter:
  uses-material-design: true